README.md, providers/active_directory.go
Hi,
To suit my needs, I add support for secure LDAP connection. I use crypto/tls library and add a boolean parameter LDAPUseSsl to activate or not the secure connection.
Hope this help.
=> Add support for secure LDAP connection

main.go
This makes the listen port for SSL respect configuration values.
=> Patch out listening on 443 to address #14

README.md, api.go, config.go, data_loader.go, http_handlers.go, main.go, providers/social.go, tap/identity-handlers/tyk_handler.go, tap/identity_handler.go, toth/toth.go
This is working with Auth0 and Okta and should theoretically form a solid baseline for SSO with any OIDC-capable provider.
Both Dashboard login and Portal login have been tested. 
It has also been modified so as to work better with the standard password policies.
=> SSO With OpenID Connect

config.go, http_handlers.go, main.go, providers/active_directory.go, providers/social.go, tap/identity-handlers/tyk_handler.go, vendor/github.com/markbates/goth/provider.go
1. http_handlers.go - 
- The same object created for different cases - so put them all together for clarity.
- getTAProvider - we used to swallow an error when creating a Provider.
- Added EmailAddress to the SSOAccessData, so we can identify users correctly in dashboard/dev portal
2. providers/social.go - set the transport so it can get /.well-known unauthorised CA 
3. providers/active_directory.go - headers tidy up
4. config.go - skip verify. explained in main.go
=> Pingid sso

README.md
Some cleanup: noticed while reading through docs.
=> quick lint

README.md
=> remove duplicate "http://http://"

config.go, main.go
This PR moves the config log after it is overriden by environment variables.
=> Log settings struct after overriding by env vars

README.md, tap/identity-handlers/tyk_handler.go, tap/profile.go
User can now specify from which field user_id is to be fetched
=> Added CustomUserIDField field in the profiles.json. 

tap/identity-handlers/tyk_handler.go, tyk-api/tyk_api.go
=> Use regular Dashbord API instead of Admin API for SSO

install/inits/systemd/system/tyk-identity-broker.service
=> Wait for network

providers/social.go
Fix https://github.com/TykTechnologies/tyk-identity-broker/issues/75
=> Allow configure OpenID scopes via `Scopes` string array

providers/active_directory.go
Initialise user rawdata map to avoid nil map assignation
=> initialise user rawdata and a few typos fixed

tyk-api/tyk_api.go
Fix https://github.com/TykTechnologies/tyk-identity-broker/issues/84
=> Fixed backward compatibility between old Admin SSO and new Dashboard SSO

tap/identity-handlers/tyk_handler.go
Instead of a space separated string, AzureAD can return an array which is unmarshalled into a []interface{}. Add an extendable function to handle that case for now.
Tested and working. With example profile:
```
[{
"ActionType": "GenerateOrLoginUserProfile",
"ID": "azure",
"OrgID": "5eb26c8c96253fbca53e2a59",
"CustomEmailField": "preferred_username",
"IdentityHandlerConfig": {
"DashboardCredential": "b74196a80f504ada5316f53b1e16d457"
},
"ProviderConfig": {
"CallbackBaseURL": "http://localhost:3010",
"FailureRedirect": "http://dash.abc:3000/?fail=true",
"UseProviders": [
{
"Key": "{CLIENT_ID",
"Secret": "{CLIENT_SECRET}",
"Scopes": ["openid", "email", "profile"],
"DiscoverURL": "https://login.microsoftonline.com/2a3490ef-c3df-4323-ae94-a75f83817991/v2.0/.well-known/openid-configuration", …
```
=> Handle user groups matching in AzureAD

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Added GH templates for: report bug, feature request and Pull request
=> added templates for bug reports, feature requests and pull request template

tap/identity-handlers/tyk_handler.go, tap/identity-handlers/tyk_handler_test.go
Added unit tests for: CustomEmailField, CustomUserIDField, CustomGroupIdField. Was done a small refactor of this logic, in order that is easier to test
None, just add test coverage
Provide unit test to this section of the profiles
```
go run -v -run TestGetEmail
go run -v -run TestGetUserID
go run -v -runTestGetGroupId
```
=> Test custom fields

README.md
1. Added explanation to the debug env var
2. Added explanation to the user-group-id. It wasn't clear which id we ask the users to set as a value
=> clarification per client's request

main.go, version.go
Version update and year update
Version update and year update
=> Year update in main.go and version bump to 1.0

tyk-api/tyk_api.go
For embeded TIB is required to pass as well a request dispatcher for admin dashboard api, this api is consumed when the request fail to the standard api. Also handled the error  throwed when is attempted to build a request without all the required parameters, in this way it will not panic.
- https://github.com/TykTechnologies/tyk-identity-broker/issues/119
- https://github.com/TykTechnologies/tyk-analytics/issues/2051 
- https://github.com/TykTechnologies/tyk-analytics/issues/2028
Give solution to:
- https://github.com/TykTechnologies/tyk-identity-broker/issues/119
- https://github.com/TykTechnologies/tyk-analytics/issues/2051 
- https://github.com/TykTechnologies/tyk-analytics/issues/2028
- In testing
=> internal tib - Ability to receive custom super-dashboard-dispatcher

utils/dist_build.sh
#Description
Also use the gpg infra that the other pipelines use.
Problem uncovered when building release-0.7.
Full [run](https://app.buddy.works/tyk-projects/tyk-identity-broker/pipelines/pipeline/171074/execution/5f318f89da64d3331fc487de) of unstable pipeline.
=> Use new signing key

tap/profile.go
Added field for Names to each profile. String and optional
https://tyktech.atlassian.net/browse/TT-218
Add a Name to profiles so FE can display them in a pretty way
CRUD profile
=> added field to save profle name

backends/in_memory_test.go, backends/redis.go, data_loader/mongo-loader.go, tap/profile.go
implemented redis backend to have in cache the profiles
https://github.com/TykTechnologies/tyk-analytics/issues/2055
https://tyktech.atlassian.net/browse/TT-262
Make TIB work correctly even in an infraestructure with replicas of dashboard behind a load balancer
- CRUD ops
=> Tt-262 implement redis backend

api.go, backends/in_memory.go, backends/in_memory_test.go, backends/mongo.go, backends/redis.go, data_loader/dumb-loader.go, data_loader/file-loader.go, data_loader/mongo-loader.go, initializer/initializer.go, providers/tapProvider.go, tap/authregister_backend.go, tap/identity-handlers/tyk_handler.go, tap/profileActions.go
Provided way to use Mongo directly without any cache for profiles. Also, provided control over organization level, so in environments such as cloud users will not be able to edit or remove accidentally non owned profiles (use case: 2 organizations that have one profile with the same ID)
https://tyktech.atlassian.net/browse/TT-262
#2055
enhance internal TIB in dashboard 
- Ran TIB as standalone
- Ran TIB as internal TIB and perform operations as: CRUD profiles, and auth flow
=> Implement mongo auth store interface

README.md
Update tib readme to include information regarding TIB
https://tyktech.atlassian.net/browse/TT-310
Update readme file with new feature
Not needed
=> Tt 310 update saml docs

backends/mongo.go, tap/profileActions.go, tyk-api/tyk_api.go
Renew session of mongo so we do not get errors like EOF
https://tyktech.atlassian.net/browse/TT-343
Give solution to https://tyktech.atlassian.net/browse/TT-343
=> TT-343 handle EOF errors coming from Mongo

backends/in_memory.go, backends/in_memory_test.go, backends/mongo.go, backends/redis.go, backends/redis_test.go, configuration/config.go
- Deprecated `Hosts` and added new `Addrs` option to redis config.
=> [TT-933] Add new addrs option to redis config and deprecate hosts

main.go
removed log line not needed where was exposed the cert file loaded
none
removed not needed log line
run app
=> removed line where was shown the cert file loaded

README.md
Updated the documentation so have better steps and clear instructions to set up SAML. I also added information to close some informational gaps.
=> SAML-Enhancement

version.go
=> updated version

tap/identity-handlers/tyk_handler.go, tap/profile.go
When some TIB profile have activated the option SSOOnlyForRegisteredUsers then only registered users will be allowed to sso into the dashboard
https://tyktech.atlassian.net/browse/TT-1490
Give solution to https://tyktech.atlassian.net/browse/TT-1490
Same as https://github.com/TykTechnologies/tyk-analytics/pull/2236
=> TT-1490 implemented logic to reject some sso users

.gitignore
To fix the problem in https://github.com/TykTechnologies/tyk-identity-broker/runs/2451358034?check_suite_focus=true
Needed for releases.
Will push an -rc tag to test.
=> Ignoring the signing key

data_loader/data_loader.go, main.go
This is in line with all the other repos and will help with automation.
Some minor changes to remove indirections needed to be made.
Fixes #162 
https://tyktech.atlassian.net/browse/TD-332
Have a common way to specify the command line config file path option in all repos managed by automation.
Tested manually, logs below:
```shellsession
% go build && ./tyk-identity-broker --conf t.conf -p p.json
[May 06 09:56:03]  WARN toth/tothic: no TYK_IB_SESSION_SECRET environment variable is set. The default cookie store is not available and any calls will fail. Ignore this warning if you are using a different store.
[May 06 09:56:03]  INFO MAIN: Tyk Identity Broker v1.2.0
[May 06 09:56:03]  INFO MAIN: Copyright Tyk Technologies Ltd 2020
[May 06 09:56:03] ERROR CONFIG: Couldn't unmarshal …
```
=> releng: [TD-332] Accept --conf for config file path

tap/identity-handlers/tyk_handler.go, tap/identity-handlers/tyk_handler_test.go, tap/profile.go
Allow users to set a character in which the user-groups claims will be splitted in. Some IDPs returns a list of groups and the way how they need to get splited changed from idp to idp, some of them use a blank space but some others (as azure) send it separated by comma, hence was added a new config option to the profiles to stablish which character do you want to use to separate the claim, it will default to blankspace to maintain backward compatibility, but you can set any character.
If you want to modify the default behavior then just add the configuration `UserGroupSeparator` in the profile, it should be a string value. Eg: `UserGroupSeparator: ","`
https://tyktech.atlassian.net/browse/TT-4685
Unblock client and be prepared for different IDPs
- Ran tests sending different groups …
=> TT-4685 support for comma separated groups claim

.github/dependabot.yml
Updated the dependabot file so it looks for updates in the gomod file. It will do so every monday of every week and will assign the pull requests to the platform squad
https://tyktech.atlassian.net/browse/TT-5749
Keep dependencies updated
----
=> TT-5749 update dependabot file so it tracks gomod dependencies

.github/workflows/release.yml, .github/workflows/sync-automation.yml
=> Deprecate set-output directive

.github/workflows/pac.yml, .gitignore, ci/repo-policy/main.tf, ci/repo-policy/modules/github-repos/repo.tf, ci/repo-policy/modules/github-repos/variables.tf
Adding terraform files for release branch management
=> TD-1462/add-gpac

.github/workflows/pac.yml, ci/repo-policy/main.tf, ci/repo-policy/modules/github-repos/repo.tf
Update backend to terraform cloud
=> Change tf backend to cloud

configuration/config.go, go.mod, go.sum, tap/identity-handlers/tyk_handler.go, tap/identity-handlers/uuid.go
=> [TT-8265] Replace satori/go.uuid lib with gofrs/uuid

version.go
=> updated the version to 1.3.2

ci/repo-policy/main.tf, ci/repo-policy/modules/github-repos/repo.tf, ci/repo-policy/modules/github-repos/variables.tf
PR auto generated by the CI Sync automation.
Picks the CI changes from the commit c239d9e803dae7e0719b997a785c4ebf79e48194
on master.
Please make any additional changes required before
merging.
=> [CI] Sync automation: Syncing commits from master

tap/authregister_backend.go
Remove references to apidef.object (#260)
* created release-1.4 branch
* removed the referrence to apidef.id
=> Merging to release-1.4: Remove references to apidef.object (#260)

go.mod, go.sum
=> upgraded storages

go.mod, go.sum
Upgraded TIB to use storage v1.0.2
=> upgraded TIB to use storage v1.0.2

configuration/config.go, data_loader/data_loader.go, go.mod, go.sum
Updating TIB with the fix from this PR: https://github.com/TykTechnologies/storage/pull/72
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-8873
=> [TT-8873] Importing Storage v1.0.3 + Adding Direct Connection

configuration/config.go, data_loader/data_loader.go, go.mod, go.sum
adding Direct Connection (#289)
=> Merging to release-1.4: adding Direct Connection (#289)

go.mod, go.sum
Updating to storage v1.0.4 (#291)
=> Merging to release-1.4: Updating to storage v1.0.4 (#291)

go.mod, go.sum
Updating to storage v1.0.5 (#293)
=> Merging to release-1.4: Updating to storage v1.0.5 (#293)

version.go
=> upgrade version.go

.gitignore
Removed the binary and updated the gitignore file to prevent in the future that this file is pushed in PRs
https://tyktech.atlassian.net/browse/TT-9443
=> TT-9443 Removed binary and updated gitignore

go.mod, go.sum
=> Merging to release-1.4: use forked saml (#331)

version.go
=> updated version to v1.4.2

initializer/initializer.go, main.go, tothic/tothic.go
Do not trigger the initialization of the session store automtically everytime that the thotic package is loaded as it lead us to get some log lines when we do not expect them or even we do not execute the app when embeded.
TT-6232
=> TT-6232 better session store handling

version.go
Created var BuiltBy that is injected by goreleaser on build time
=> created BuiltBy which is injected by goreleaser in build time

data_loader/mongo_loader.go, tyk-api/tyk_api.go
Handle some cases where someone starting to use TIB as standalone will have issues creating their new first profile
https://tyktech.atlassian.net/browse/TT-10884
=> TT-10884 better err handling

api.go, backends/in_memory.go, backends/mongo.go, configuration/config_test.go, constants/constants.go, data_loader/data_loader_test.go, data_loader/file_loader.go, data_loader/mongo_loader.go, error/error.go, providers/active_directory.go, providers/saml_test.go, providers/social.go, providers/util_slug.go, tap/action.go, tap/identity-handlers/dummy_handler.go, tap/identity-handlers/tyk_handler.go, tap/identity-handlers/tyk_handler_test.go, tap/identity_handler.go, tap/profile.go, tap/profileActions.go, tap/provider_type.go, tap/ta_provider.go, toth/toth.go, tothic/tothic.go, tyk-api/tyk_api.go
Govet-gofmt and goimports source code
TT-10886
=> TT-10886 formated code

.github/workflows/release.yml, go.mod, go.sum, repo-policy/main.tf
Upgraded go version to go 1.21
TT-10674
In order to keep up to date and in sync with other tyk components, upgraded the go version
Compile app
=> TT-10674 upgraded go version

backends/redis.go, configuration/config.go, configuration/config_test.go
Added TLS configs for redis 
TT-10521
=> TT-10521 added tls confis

go.mod, go.sum
=> upgrade storage to v1.1.0

configuration/config.go, configuration/config_test.go
Tyk v3/v4 does not work with MongoDB v5. Before Mongo DB 4.4 will get EOL by Feb 2024, so we are updating our default MongoDB driver to mongo-go from Tyk 5.3.
https://tyktech.atlassian.net/browse/TT-10409?atlOrigin=eyJpIjoiODdjODE2MTc4M2M1NGRiNmJkZWFhYmNjM2NlMjE1OWUiLCJwIjoiaiJ9
=> [TT-10409] Updating default Mongo driver to mongo-go

version.go
=> updated version to 1.5

tothic/tothic.go
=> TT-11242 When setting SSO flows params in redis, convert them to string

tothic/tothic.go
when setting params convert them to string (#384)
=> Merging to release-1.5: when setting params convert them to string (#384)

version.go
Changing Version variable to v1.5.1
=> Changing Version variable to v1.5.1

version.go
changing Version variable to v1.5.1 (#386)
=> Merging to release-1.5: changing Version variable to v1.5.1 (#386)

.github/workflows/release.yml, ci/Dockerfile.distroless, ci/goreleaser/goreleaser.yml
=> [SYSE-370 master] June template application

backends/redis.go, backends/redis_test.go, tothic/tothic.go
SetKey in RedisBackend accepts now interfaces that are not string anattempt to stringtify them. It was only breaking change for apps importing TIB not for end customers
TT-12344
=> TT-12344 Resolve Unmarshalling Error for PathParams Post-Breaking Change

internal/jwe/JWE.go
renamed profile option PrivateKeyLocation (#423)
Co-authored-by: sredny buitrago <sredny@srednys-MacBook-Pro.local>
=> Merging to release-1.6: renamed profile option PrivateKeyLocation (#423)

.github/workflows/ci-tests.yml, version.go
=> update version to v1.7.0
