TykTechnologies/tyk-identity-broker

- .dockerignore
- docker/Dockerfile
- docker/hooks/build
This includes a build hook for the Docker Hub so that it would automatically infer the package version from the version.go file and pass it as an argument to docker build.
Solves #23.
> Dockerfile for the public image

- http_handlers.go
- main.go
Health checks are required in order to use gcloud load balancing and/or ingresses for GKE. This pr adds a health check endpoint at `/health` that simply returns a 200 ok code
> Add Health Check

- docker/Dockerfile
- docker/hooks/build
The build process looks like this:
Buddy pipeline creates the unstable packages on push to master ->
Triggers an `unstable` tag build on docker hub via a webhook ->
The build hook on docker hub determines if it's an `unstable` tag and then switches to the corresponding package repository, taking the latest version too, passing all that as args to `docker build`
> Add support for unstable Docker image builds

- README.md
- providers/active_directory.go
Now you can do a bind with admin user who are allowed to do a search,
and later it will bind one more time but with user DN.
Example profile:
```
{
"ActionType": "GenerateOrLoginUserProfile",
"ID": "4",
"OrgID": "59fc80d9158519599ca23cfc",
"ProviderConfig": {
"FailureRedirect": "https://tyk-dashboard:3000/?fail=true",
"LDAPAttributes": [],
"LDAPPort": "389",
"LDAPAdminUser": "admin",
"LDAPAdminPassword": "password",
"LDAPServer": "localhost",
"LDAPUserDN": "uid=*USERNAME*,dc=example,dc=org"
},
"ProviderName": "ADProvider",
"ReturnURL": "https://tyk-dashboard:3000/tap",
"Type": "passthrough"
}
```
Additionally made a fix to always retrieve LDAP user email, since email
can be retrieed only when search is made. Fix is
basically setting "LDAPFilter" to `"(objectclass=*")` if its empty (same …
> Add flow to allow initial bind by admin user

- config.go
- tothic/tothic.go
- tothic/tothic_test.go
This PR deprecates `SESSION_SECRET`. Also, it doesn't break backward compatibility.  It still supports  `SESSION_SECRET`. `TYK_IB_SESSION_SECRET` overrides if both set. 
Fixes #48
> Deprecate SESSION_SECRET, add TYK_IB_SESSION_SECRET

- tap/identity-handlers/tyk_handler.go
Since we set "email" with the default one, we didn't get to the line with "email = gUser.Email"
> we didnt assigned the user's email since it was initialised with the default email

- providers/social.go
- vendor/github.com/markbates/goth/providers/salesforce/salesforce.go
- vendor/github.com/markbates/goth/providers/salesforce/session.go
Fixes #60 
A new provider type `salesforce` is added to in Social Provider for Salesforce IDp.
Example Config
```json
{
"ActionType": "GenerateOrLoginDeveloperProfile",
"ID": "4",
"IdentityHandlerConfig": {
"DashboardCredential": ""
},
"OrgID": "5cd00524d85f245425510a78",
"ProviderConfig": {
"CallbackBaseURL": "http://localhost:3010",
"FailureRedirect": "https://www.tyk-dashboard.com:3000/?fail=true",
"UseProviders": [{
"Name": "salesforce",
"Key": "xxxx",
"Secret": "xxxxx",
"DiscoverURL": ""
}]
},
"ProviderConstraints": {
"Domain": "",
"Group": ""
},
"ProviderName": "SocialProvider",
"ReturnURL": "http://portal:3000/portal/sso/",
"Type": "redirect"
}
```
> Add support of salesforce provider

- utils/dist_build.sh
This allows us to use the official golang 1.12 images rather than
having to install it by hand on jessie.
rpm-sign.sh is on BuddyFS/build_tools.
> Signing rpms using gpg2 and the agent

- tyk-api/tyk_api.go
Even if client.Do request fails, we are accessing response Code. 
According to http docs, 
`A non-nil Response with a non-nil error only occurs when CheckRedirect fails, and even then the returned Response.Body is already closed.`
which is never going to happen in our case.
> Avoid goroutine panics if gateway/dashboard is not running

- config.go
Redis SSL fields aren't populated when calling `newRedisClusterPool`, this fixes the issue, the following configuration now works:
```json
{
"Secret": "test-secret",
"HttpServerOptions": {
"UseSSL": false,      
"CertFile": "./certs/server.pem",
"KeyFile": "./certs/server.key"
},
"BackEnd": {
"Name": "redis",
"ProfileBackendSettings": {},
"IdentityBackendSettings": {
"Hosts" : {
"localhost": "6379"
},
"UseSSL": true,
"SSLInsecureSkipVerify": true,
"Password": "testpassword",
"Database": 0,
"EnableCluster": false,
"MaxIdle": 1000,
"MaxActive": 2000
}
},
"TykAPISettings": {
"GatewayConfig": {
"Endpoint": "http://localhost",
"Port": "80",
"AdminSecret": "54321"
},
"DashboardConfig": {
"Endpoint": "http://localhost",
"Port": "3000",
"AdminSecret": "12345"
}
}
}
```
> Fix Redis SSL fields

- tap/identity-handlers/tyk_handler.go
- tap/profile.go
Fix https://github.com/TykTechnologies/tyk-identity-broker/issues/32
You can set static value via `DefaultGroupID` or dynamic value based on field of oAuth/OpenID scope using `CustomUserGroupField` and `UserGroupMapping` fields. Example:
```
{
"DefaultUserGroupID": "<default-user-group>",
"CustomUserGroupField": "scope",
"UserGroupMapping": {
"admin": "<admin-group-id>",
"analytics": "<analytics-group-id>"
}
}
```
> Add support for specifying user group id

- providers/active_directory.go
Now you can use attributes like `CustomUserGroupField`, since they read from custom fields.
> Fill rawData attributes for LDAP

- data_loader/data-loader.go
- log/log.go
Added a proper format to the logger and not leeave it as default. It was presenting logs like:
`INFO[0000] Loaded profiles from Mongo                    prefix="TIB DATA LOADER"`
So, some information as timestamp is missing there, this PR fix that and now the logs printed looks like:
`[Feb 20 10:38:00]  INFO TIB DATA LOADER: Loaded profiles from Mongo`
> Set log format

- tap/profileActions.go
on tap profiles, anytime that we use a CRUD operation then we expect a descriptive status code in the response. The main issue here was that on Update and Delete if the object doesnt exist then we were returning status code 400 instead 404, this PR fixes that
> on api for CRUD profiles, return the proper status code

- Initializer/initializer.go
- backends/in_memory.go
- backends/redis.go
- configuration/config.go
- data_loader/data-loader.go
- data_loader/mongo-loader.go
- error/error.go
- log/log.go
- providers/active_directory.go
- providers/proxy.go
- providers/reverse_proxy.go
- providers/social.go
- providers/tapProvider.go
- tap/identity-handlers/dummy_handler.go
- tap/identity-handlers/tyk_handler.go
- tyk-api/tyk_api.go
In order to maintain the same format of the logs in dashboard, we needed the ability to receive a logger as param and use that one, also, we need to ensure that if the logger was set, then tib packages will reload their logger to get the new configs.
Some of the changes performed in this PR includes a function to reload the logger inside a `sync.Once` statement, this was made in this way to only reload the logger the minimum as possible.  The reason why not only receive log configs as param is that its not only about format of the information but the Log Level can be set in the main app and we need to inherit that as well.
This PR unblocks: https://github.com/TykTechnologies/tyk-analytics/pull/1884
Ticket related: https://github.com/TykTechnologies/tyk-identity-broker/issues/97
**Pull …
> Add ability to receive logger from external app

- tap/identity-handlers/tyk_handler.go
Currently if a user exists in Tyk that an IDP user email matches to from a custom field it will never get set.
> Change logic so we dont override when email set from custom field

- data_loader/mongo-loader.go
When the data store is mongo, and the last profile is removed then we receive an error related to the flush function, but the profile is removed correctly. The error is because we attempt to insert zero records to mongo.
This PR gives partial solution to: https://github.com/TykTechnologies/tyk-analytics/issues/1913
In order to give compete solution we only need to update the vendor directory
> on flush using mongo, check that we have more than zero profiles to attempt mongo insertion

- providers/saml.go
- tap/identity-handlers/tyk_handler.go
profiles.json
```
{
...
"CustomUserGroupField": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
"UserGroupMapping": {
"7149b3c0-5e5d-48b3-a42a-c73ded0bc232": "5f034003ed3dc300012e48a0",
"ab776d34-1d4c-4ee0-9f4b-9a9cae029f4e": "5f033fa1ed3dc300012e489f"
}
...
}
```
> Adding SAML role support for Dashboard Users Groups. Example:

- constants/constants.go
- http_handlers.go
- main.go
- providers/active_directory.go
- providers/proxy.go
- providers/saml.go
- providers/social.go
- providers/tapProvider.go
- tap/identity-handlers/tyk_handler.go
- tap/ta_provider.go
Fixes https://github.com/TykTechnologies/tyk-identity-broker/issues/7
Docs PR here: https://github.com/TykTechnologies/tyk-docs/pull/1256
- Tested with AzureAD and samltest.id
Docs: 
**SSO with SAML and Tyk**
SAML authentication is a way for a service provider, such as the Tyk Dashboard or Portal, to assert the Identity of a User via a third party.
Tyk Identity Broker can act as the go-between for the Tyk Dashboard and Portal and a third party identity provider. Tyk Identity broker can also interpret and pass along information about the user who is logging in such as Name, Email and group or role metadata for enforcing role based access control in the Tyk Dashboard.
The provider config for SAML has the following values that can be configured in a Profile:
`SAMLBaseURL` - The host of TIB …
> SAML provider for TIB

- main.go
- tyk-api/tyk_api.go
for POCs is need sometimes to set skipTLSVerify:true and therefore have the ability to use self signed certificates.
https://github.com/TykTechnologies/tyk-identity-broker/issues/102
Give solution to https://github.com/TykTechnologies/tyk-identity-broker/issues/102
- Ran dashboard and TIB in HTTPS
- in TIB config file set `config.HttpServerOptions.SSLInsecureSkipVerify:true`
- Call TIB with `curl --location -vk --request POST 'https://localhost:3010/auth/ldap-for-sso-dashboard/ADProvider?username=read-only-admin&password=password'
- Nonce is created and a URL to login to dev portal comes in the response
Response:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3010 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify …
```
> skipTLSVerify while consuming dashboard api {do not merge}

- providers/saml.go
When log level is Debug, dont panic when `log.Debug` is called
https://tyktech.atlassian.net/browse/TT-265
Give solution to https://tyktech.atlassian.net/browse/TT-265
- Follow reproduction steps described in ticket
> TT-265 when log level is debug, dont panic in saml

- backends/in_memory_test.go
- backends/redis.go
- http_handlers.go
- initializer/initializer.go
- main.go
- providers/active_directory.go
- providers/proxy.go
- providers/saml.go
- providers/social.go
- providers/tapProvider.go
- tap/profile.go
- tap/ta_provider.go
- tothic/tothic.go
thotic saves the relation of path params with providers using a map, this was moved to use redis for internal tib so it works ok in internal tib with a load balancer. It also was considered the multi-org environment, hence the implementation of redis keys considering the orgId
https://tyktech.atlassian.net/browse/TT-262
give solution to https://tyktech.atlassian.net/browse/TT-262
- Ran TIB in internal and external tib
- connect internal tib with redis, and check that the full flow works. External TIB also initializes with redis as default
- created 2 social profiles (This PR affects directly the social providers). Was created one for dashboard sso access using github, and another with open-id using azure. Here I attach the profiles:
Using azure:
```
{
"ID": "open-id-dashboard",
"OrgID": …
```
> Tt 262 move in memory path params to redis 

- providers/proxy.go
TIB's proxy flow does not work if any upstream service that verifies Host headers against Expected Host headers will fail, such as the Google Suite APIs.  That's because Tyk does not insert Upstream Host header's into the call like it is supposed to.
> modify host header to match upstream host

- providers/proxy.go
At the moment developer portal access with Proxy provider is broken because Developer SSO requires email.
This PR is relatively simple: if a username is already an email use it, otherwise build it as `uName + "@soSession.com"`
@sedkis confirmed it is working
> [TT-1129] Fix proxy provider with email.

- log/log.go
The dashboard tests failed because of the race condition in this project. See: https://github.com/TykTechnologies/tyk-analytics/pull/2229/checks?check_run_id=2168176475
> Fix data race in log.Get

- providers/active_directory.go
- tap/identity-handlers/tyk_handler.go
implemented dynamic group mapping for AD provider.
https://support.tyk.io/hc/requests/11700
After deserializing ldap response with user info previous implementation of ADProvider was grabbing the first element from user attribute with type array and hence all valuable group membership information was cutted off.
* fixed ADProvider
* added handler for []string array of AD groups @ tyk_handler.go:groupStringer function
* minor code style improvements
Ran TIB as standalone, AD, dashboard. Used the following profile for test:
```json
[
{
"ActionType": "GenerateOrLoginUserProfile",
"ID": "1",
"OrgID": "5f48ae5f62a1be5a74f39377",
"IdentityHandlerConfig": {
"DashboardCredential": ""
},
"ProviderConfig": {
"LDAPUseSSL": false,
"FailureRedirect": "{{ failure redirect }}",
"LDAPPort": "389", …
```
> add dynamic group mapping for AD provider

- .github/workflows/release.yml
This should resolve the problem reported in https://tyktech.slack.com/archives/CKARCGLEM/p1642640267066300
https://github.com/TykTechnologies/tyk-identity-broker/runs/4875941393?check_suite_focus=true was the last run.
> packagecloud-action@v1.1 uses the older API

- go.mod
- go.sum
upgraded TIB to use storage v1.0.2 (#276)
> Merging to release-1.4: upgraded TIB to use storage v1.0.2 (#276)

- main.go
- version.go
These variables are set at build time. These changes help the releng templates use a standard build argument. See
https://tyktech.slack.com/archives/C03PT641CF9/p1699582096160529
> [SYSE-294] Standardise build time variables

- .github/workflows/ci-tests.yml
CIs are failing because version 2 was deprecated.
> Upgrading upload-artifact to v3

- internal/jwe/JWE.go
rename from private_key_location to PrivateKeyLocation
https://tyktech.atlassian.net/browse/TT-13453
> renamed profile option PrivateKeyLocation

- tap/identity-handlers/tyk_handler.go
- tap/identity-handlers/tyk_handler_test.go
> TT-9366 added new field groupsIds in SSOAccessData
